name: Master CI/CD
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  cd:
    runs-on: ubuntu-latest
    # needs: ci
    steps:
      - uses: actions/checkout@v1
      - name: Docker login
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build
        run: docker build -t mkdocs .
      - name: Tags
        run: |
          docker tag ansible-lint ${{ github.repository }}:${{ github.sha }}
          docker tag ansible-lint ${{ github.repository }}:dev
      - name: check install
        run: |
          docker images
          docker run --rm ${{ github.repository }}:${{ github.sha }} mkdocs -V
          docker run --rm ${{ github.repository }}:${{ github.sha }} ssh -V
          docker run --rm ${{ github.repository }}:${{ github.sha }} bash --version
      - name: Push
        run: |
          docker push ${{ github.repository }}:${{ github.sha }}
          docker push ${{ github.repository }}:dev